### ISSUE TITLE
rnftools liftover - AssertionError - assert (last_right1 is None) or (last_right1==left1)

### ISSUE THREAD

**Issue by karel-brinda** [karel-brinda/rnftools#56]
```
(dymas) On-y-go-2:exp1.11__0.07-ococo16-noremap karel$ "/Users/karel/.smbl/bin/samtools" view -h "2_alignments.dyn/3.1_unsorted_bam/00002.bam" | "../../dymas/dymas/filter_aligned_rnf_reads.py" -i 13 - - | rnftools liftover --faidx "2_alignments.dyn/1_reference/00000.fa.fai" --chain "2_alignments.dyn/6.1_basic_chain/00000.chain" --genome-id 1 - -
Traceback (most recent call last):
  File "/Users/karel/miniconda3/envs/dymas/bin/rnftools", line 10, in <module>
    sys.exit(rnftools_script())
  File "/Users/karel/miniconda3/envs/dymas/lib/python3.4/site-packages/rnftools/scripts.py", line 979, in rnftools_script
    args.func(args)
  File "/Users/karel/miniconda3/envs/dymas/lib/python3.4/site-packages/rnftools/scripts.py", line 697, in liftover
    invert=args.invert,
  File "/Users/karel/miniconda3/envs/dymas/lib/python3.4/site-packages/rnftools/rnfformat/RnfLifter.py", line 19, in __init__
    self._chain=rnftools.utils.Chain(chain_fo=chain_fo,invert=invert)
  File "/Users/karel/miniconda3/envs/dymas/lib/python3.4/site-packages/rnftools/utils/Chain.py", line 96, in __init__
    name2=qName,
  File "/Users/karel/miniconda3/envs/dymas/lib/python3.4/site-packages/rnftools/utils/ChainSequence.py", line 25, in __init__
    assert (last_right1 is None) or (last_right1==left1)
AssertionError
Traceback (most recent call last):
  File "../../dymas/dymas/filter_aligned_rnf_reads.py", line 42, in <module>
    args.output_sam_fo.write(x)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by karel-brinda** [comment]
Chain file:
```
chain 230218 I 230218 + 0 230218 I 230218 + 0 230218 1
230218

chain 813184 II 813184 + 0 813184 II 813184 + 0 813184 2
813184

chain 316620 III 316620 + 0 316620 III 316620 + 0 316620 3
316620

chain 1531933 IV 1531933 + 0 1531933 IV 1531933 + 0 1531933 4
1531933

chain 576874 V 576874 + 0 576874 V 576874 + 0 576874 5
576874

chain 270161 VI 270161 + 0 270161 VI 270161 + 0 270161 6
270161

chain 85779 Mito 85779 + 0 85779 Mito 85779 + 0 85779 7
85779
```

Reference genome:
ftp://ftp.ensemblgenomes.org/pub/fungi/release-33/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz
